apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yojanamitra-ingress
  namespace: yojanamitrA
spec:
  rules:
    - host: yojanamitra.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80

