import type { Scheme } from '@/components/SchemeCard';

export const SCHEMES: Scheme[] = [
    {
        id: 'pm-kisan',
        name: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
        nameHi: 'प्रधानमंत्री किसान सम्मान निधि',
        ministry: 'Ministry of Agriculture & Farmers Welfare',
        category: 'farmer',
        state: 'All India',
        description: 'Provides income support of ₹6,000 per year in three equal installments to all landholding farmer families to supplement their financial needs for procuring agricultural inputs.',
        benefit: '₹6,000 per year (₹2,000 every 4 months)',
        eligibility: 'All landholding farmer families with cultivable land. Annual family income below ₹2 lakh.',
        tags: ['income support', 'agriculture', 'direct benefit transfer'],
        matchScore: 92,
    },
    {
        id: 'nsp-merit',
        name: 'National Scholarship Portal – Merit Scholarship',
        nameHi: 'राष्ट्रीय छात्रवृत्ति पोर्टल – मेरिट स्कॉलरशिप',
        ministry: 'Ministry of Education',
        category: 'student',
        state: 'All India',
        description: 'Central sector scholarship scheme for college and university students from economically weaker sections.',
        benefit: 'Up to ₹20,000 per year scholarship',
        eligibility: 'Students who passed 12th with 80%+ marks; family income below ₹4.5 lakh/year.',
        tags: ['scholarship', 'education', 'meritorious'],
        matchScore: 85,
    },
    {
        id: 'pm-ujjwala',
        name: 'PM Ujjwala Yojana 2.0',
        nameHi: 'प्रधानमंत्री उज्ज्वला योजना 2.0',
        ministry: 'Ministry of Petroleum & Natural Gas',
        category: 'women',
        state: 'All India',
        description: 'Provides free LPG connections to women from poor households to protect health and environment.',
        benefit: 'Free LPG connection + first refill + stove',
        eligibility: 'Women from BPL households. Adult woman not already possessing domestic LPG connection.',
        tags: ['LPG', 'women empowerment', 'BPL'],
        matchScore: 78,
    },
    {
        id: 'startup-india-seed',
        name: 'Startup India Seed Fund Scheme',
        nameHi: 'स्टार्टअप इंडिया सीड फंड स्कीम',
        ministry: 'Department for Promotion of Industry and Internal Trade',
        category: 'startup',
        state: 'All India',
        description: 'Financial assistance to startups for proof of concept, prototype development, product trials, market entry and commercialization.',
        benefit: 'Up to ₹20 lakh for proof of concept; ₹50 lakh for commercialization',
        eligibility: 'DPIIT-recognized startup less than 2 years old. Not received funding from government schemes above ₹10 lakh.',
        tags: ['startup', 'seed fund', 'entrepreneurship'],
        matchScore: 70,
    },
    {
        id: 'ayushman-bharat',
        name: 'Ayushman Bharat – PM-JAY',
        nameHi: 'आयुष्मान भारत – प्रधानमंत्री जन आरोग्य योजना',
        ministry: 'Ministry of Health & Family Welfare',
        category: 'health',
        state: 'All India',
        description: 'World\'s largest health insurance scheme providing ₹5 lakh health coverage per family per year to poor and vulnerable families.',
        benefit: '₹5 lakh health insurance coverage per year',
        eligibility: 'Families included in SECC 2011 database. BPL families, scheduled castes, scheduled tribes.',
        tags: ['health insurance', 'hospitalization', 'BPL'],
        matchScore: 88,
    },
    {
        id: 'pm-awas-gramin',
        name: 'PM Awas Yojana – Gramin',
        nameHi: 'प्रधानमंत्री आवास योजना – ग्रामीण',
        ministry: 'Ministry of Rural Development',
        category: 'housing',
        state: 'All India',
        description: 'Provides financial assistance to rural BPL families for constructing basic houses with basic amenities.',
        benefit: '₹1.2 lakh (plains) to ₹1.3 lakh (hilly areas) for house construction',
        eligibility: 'Rural households without pucca house. Priority to SC/ST, minorities, disabled, widows.',
        tags: ['housing', 'rural', 'BPL'],
        matchScore: 75,
    },
    {
        id: 'mudra-yojana',
        name: 'Pradhan Mantri MUDRA Yojana',
        nameHi: 'प्रधानमंत्री मुद्रा योजना',
        ministry: 'Ministry of Finance',
        category: 'startup',
        state: 'All India',
        description: 'Provides loans to non-corporate, non-farm small/micro enterprises for income generation and employment creation.',
        benefit: 'Shishu: up to ₹50,000 | Kishor: ₹50K–₹5L | Tarun: ₹5L–₹10L',
        eligibility: 'Non-farm micro enterprises, small businesses, self-employed individuals. No collateral required.',
        tags: ['loan', 'MSME', 'entrepreneurship'],
        matchScore: 82,
    },
    {
        id: 'beti-bachao-padao',
        name: 'Beti Bachao Beti Padhao',
        nameHi: 'बेटी बचाओ बेटी पढ़ाओ',
        ministry: 'Ministry of Women & Child Development',
        category: 'women',
        state: 'All India',
        description: 'Scheme to address declining child sex ratio and promote girl child education and empowerment.',
        benefit: 'Financial support for girl child education, scholarships, and health benefits',
        eligibility: 'All girl children from birth to 18 years. Special focus on districts with low sex ratio.',
        tags: ['girl child', 'education', 'empowerment'],
        matchScore: 65,
    },
    {
        id: 'kcc',
        name: 'Kisan Credit Card (KCC)',
        nameHi: 'किसान क्रेडिट कार्ड',
        ministry: 'Department of Financial Services, Ministry of Finance',
        category: 'farmer',
        state: 'All India',
        description: 'Provides farmers with affordable credit for their agricultural operations, allied activities, and non-farm activities.',
        benefit: 'Credit up to ₹3 lakh at 4% interest rate (with interest subvention)',
        eligibility: 'Farmers, tenant farmers, oral lessees, share croppers, SHG members engaged in agriculture.',
        tags: ['credit', 'agriculture', 'loan'],
        matchScore: 80,
    },
    {
        id: 'iay-housing',
        name: 'PM Awas Yojana – Urban',
        nameHi: 'प्रधानमंत्री आवास योजना – शहरी',
        ministry: 'Ministry of Housing & Urban Affairs',
        category: 'housing',
        state: 'All India',
        description: 'Affordable housing for urban poor through interest subsidy on housing loans and construction of new houses.',
        benefit: 'Interest subsidy up to 6.5% on home loans. Upto ₹2.67 lakh benefit',
        eligibility: 'EWS/LIG/MIG households without pucca house. Annual income criteria apply.',
        tags: ['housing', 'urban', 'affordable'],
        matchScore: 68,
    },
];

export const INDIAN_STATES = [
    'All States', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
    'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala',
    'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
    'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
    'Uttarakhand', 'West Bengal', 'Delhi', 'Jammu & Kashmir', 'Ladakh',
];

export const CATEGORIES = [
    { value: 'all', label: 'All Categories', labelHi: 'सभी श्रेणियाँ', icon: '📋' },
    { value: 'farmer', label: 'Farmer', labelHi: 'किसान', icon: '🌾' },
    { value: 'student', label: 'Student', labelHi: 'छात्र', icon: '🎓' },
    { value: 'women', label: 'Women', labelHi: 'महिला', icon: '👩' },
    { value: 'startup', label: 'Startup / Business', labelHi: 'स्टार्टअप', icon: '🚀' },
    { value: 'health', label: 'Health', labelHi: 'स्वास्थ्य', icon: '🏥' },
    { value: 'housing', label: 'Housing', labelHi: 'आवास', icon: '🏠' },
];
